/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class StorageCategoryUsage {
  public String category;
  public Long bytes;
  public Long evictableBytes;
  public Long files;
}
