/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class StorageChatUsage {
  public Integer chatId;
  public String name;
  public Long bytes;
  public Long evictableBytes;
  public Long files;
  public Long lastTimestamp;
}
