/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

public class StorageClearResult {
  public Long freedBytes;
  public Long clearedFiles;
  public Long clearedMessages;
  public Long skippedFiles;
  public Long skippedBytes;
}
