/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

import java.util.List;

public class StorageUsage {
  public Long totalBytes;
  public Long databaseBytes;
  public Long blobdirBytes;
  public Long evictableBytes;
  public List<StorageCategoryUsage> byCategory;
  public List<StorageChatUsage> byChat;
}
