/* Autogenerated file, do not edit manually */
package chat.delta.rpc.types;

import java.util.List;

public class StorageClearRequest {
  public List<String> categories;
  public List<Integer> chatIds;
  public Long olderThanSeconds;
  public Long limitBytes;
}
