import Foundation
import UIKit
import DcCore
import LocalAuthentication

extension URL {
    var isDeltaChatInvitation: Bool {
        return Utils.isInviteHost(self.host)
    }
}
struct Utils {
    /// Canonical BMChat invite link components — the BMChat VPS at IP
    /// `5.187.4.132`, plain HTTP, path `/i`. The cryptographic payload lives
    /// in the URL fragment and never reaches the server.
    public static let inviteScheme = "http"
    public static let inviteHost   = "5.187.4.132"
    public static let invitePath   = "/i"
    public static let inviteLinkPrefix = inviteScheme + "://" + inviteHost + invitePath
    /// Legacy hosts that BMChat still recognises in incoming invites so QR
    /// codes generated by older builds keep working.
    public static let legacyInviteDomains = ["i.bmchat.example", "i.delta.chat"]
    /// Backwards-compatibility shim — older Swift code references this.
    public static let inviteDomain = inviteHost
    public static let legacyInviteDomain = "i.delta.chat"

    private static func legacyPrefixes(for host: String) -> [String] {
        return [
            "https://" + host + "/#",
            "https://" + host + "#",
            "http://"  + host + "/#",
            "http://"  + host + "#",
        ]
    }

    /// Returns true when the given URL host (with any scheme) is one that
    /// BMChat treats as an invite link host.
    public static func isInviteHost(_ host: String?) -> Bool {
        guard let host else { return false }
        if host == inviteHost { return true }
        return legacyInviteDomains.contains(host)
    }

    /// Rewrites any legacy/upstream invite URL to the canonical BMChat link
    /// `http://5.187.4.132/i#…`.
    public static func rewriteInviteLink(_ link: String?) -> String? {
        guard let link else { return nil }
        for host in legacyInviteDomains {
            for legacy in legacyPrefixes(for: host) {
                if link.hasPrefix(legacy) {
                    return inviteLinkPrefix + "#" + String(link.dropFirst(legacy.count))
                }
            }
        }
        return link
    }

    /// Removes Delta-Chat artwork (footer wordmark, "δ" centerpiece overlay)
    /// embedded in QR-code SVGs by the bundled native core, and rewrites any
    /// legacy invite hyperlinks contained within.
    public static func stripDeltaBranding(in svg: String) -> String {
        var out = svg.replacingOccurrences(of: ">get.delta.chat<", with: ">BMChat<")
        let footerPath = #"<path[^>]*id=\"path84310\"[^>]*/>"#
        if let regex = try? NSRegularExpression(pattern: footerPath, options: [.dotMatchesLineSeparators]) {
            let range = NSRange(out.startIndex..., in: out)
            out = regex.stringByReplacingMatches(in: out, range: range, withTemplate: "")
        }
        let centerpiece = #"<g[^>]*transform=\"scale\(1\.1342891,0\.88160947\)\"[^>]*>[\s\S]*?</g>"#
        if let regex = try? NSRegularExpression(pattern: centerpiece, options: [.dotMatchesLineSeparators]) {
            let range = NSRange(out.startIndex..., in: out)
            out = regex.stringByReplacingMatches(in: out, range: range, withTemplate: "")
        }
        for host in legacyInviteDomains {
            out = out.replacingOccurrences(of: "https://" + host, with: inviteLinkPrefix)
            out = out.replacingOccurrences(of: "http://"  + host, with: inviteLinkPrefix)
        }
        return out
    }

    // MARK: - Proxy

    static func isProxy(url proxyURL: URL, dcContext: DcContext) -> Bool {
        let parsedProxy = dcContext.checkQR(qrCode: proxyURL.absoluteString)

        return parsedProxy.state == DC_QR_PROXY
    }

    // MARK: - Email
    static func isEmail(url: URL) -> Bool {
        let mailScheme = "mailto"
        if let scheme = url.scheme {
            return mailScheme == scheme && DcContext.mayBeValidAddr(email: url.absoluteString.substring(mailScheme.count + 1, url.absoluteString.count))
        }
        return false
    }

    static func getEmailFrom(_ url: URL) -> String {
        let mailScheme = "mailto"
        return url.absoluteString.substring(mailScheme.count + 1, url.absoluteString.count)
    }

    public static func getBackgroundImageURL(name: String) -> URL? {
        let fileManager = FileManager.default
        let urls = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask) as [URL]
        guard let identifier = Bundle.main.bundleIdentifier else {
            logger.error("backgroundImageURL: Could not find bundle identifier")
            return nil
        }
        guard let directoryURL = urls.last else {
            logger.error("backgroundImageURL: Could not find directory url for .applicationSupportDirectory in .userDomainMask")
            return nil
        }
        return directoryURL.appendingPathComponent(identifier).appendingPathComponent(name)
    }

    public static func getSafeBottomLayoutInset() -> CGFloat {
        let window = UIApplication.shared.windows.first
        return window?.safeAreaInsets.bottom ?? 0
    }

    public static func getInviteLink(context: DcContext, chatId: Int) -> String? {
        return rewriteInviteLink(context.getSecurejoinQr(chatId: chatId))
    }

    public static func share(message: DcMsg, parentViewController: UIViewController, sourceView: UIView? = nil, sourceItem: UIBarButtonItem? = nil) {
        guard let scrambledURL = message.fileURL else { return }

        let shareURL: URL
        if let filename = message.filename {
            let cleanURL = FileManager.default.temporaryDirectory.appendingPathComponent(filename)
            shareURL = FileHelper.copyIfPossible(src: scrambledURL, dest: cleanURL)
        } else {
            shareURL = scrambledURL
        }

        let objectsToShare: [Any]
        if message.type == DC_MSG_WEBXDC {
            let dict = message.getWebxdcInfoDict()
            let previewImage = message.getWebxdcPreviewImage()
            let previewText = dict["name"] as? String ?? shareURL.lastPathComponent
            objectsToShare = [WebxdcItemSource(title: previewText,
                                               previewImage: previewImage,
                                               url: shareURL)]
        } else {
            objectsToShare = [shareURL]
        }

        let activityVC = UIActivityViewController(activityItems: objectsToShare, applicationActivities: nil)
        activityVC.excludedActivityTypes = [.copyToPasteboard]
        if let sourceItem {
            activityVC.popoverPresentationController?.barButtonItem = sourceItem
        } else if let sourceView {
            activityVC.popoverPresentationController?.sourceView = sourceView
        } else {
            logger.error("set sourceView or sourceItem to avoid iPad crashes")
            return
        }
        parentViewController.present(activityVC, animated: true, completion: nil)
    }

    public static func share(url: String, parentViewController: UIViewController, sourceItem: UIBarButtonItem) {
        guard let url = URL(string: url) else { return }

        Utils.share(url: url, parentViewController: parentViewController, sourceItem: sourceItem)
    }

    public static func share(text: String, parentViewController: UIViewController, sourceItem: UIBarButtonItem) {
        guard let textData = text.data(using: .utf8) else { return }

        // UTF-8 byte order mark, commonly seen in text files. See [List Of file signatures](https://en.wikipedia.org/wiki/List_of_file_signatures)
        var data = Data([0xEF, 0xBB, 0xBF])
        data.append(textData)

        let tempLogfileURL = FileManager.default.temporaryDirectory.appendingPathComponent("deltachat-log.txt")
        try? FileManager.default.removeItem(at: tempLogfileURL)
        try? data.write(to: tempLogfileURL)
        
        Utils.share(url: tempLogfileURL, parentViewController: parentViewController, sourceItem: sourceItem)
    }

    public static func share(url: URL, parentViewController: UIViewController, sourceItem: UIBarButtonItem) {
        let activityVC = UIActivityViewController(activityItems: [url], applicationActivities: nil)
        activityVC.popoverPresentationController?.barButtonItem = sourceItem
        parentViewController.present(activityVC, animated: true, completion: nil)
    }

    public static func share(text: String, parentViewController: UIViewController, sourceView: UIView) {
        let activityVC = UIActivityViewController(activityItems: [text], applicationActivities: nil)
        activityVC.popoverPresentationController?.sourceView = sourceView // iPad crashes without a source
        parentViewController.present(activityVC, animated: true, completion: nil)
    }

    public static func share(url: URL, parentViewController: UIViewController, sourceView: UIView) {
        let activityVC = UIActivityViewController(activityItems: [url], applicationActivities: nil)
        activityVC.popoverPresentationController?.sourceView = sourceView // iPad crashes without a source
        parentViewController.present(activityVC, animated: true, completion: nil)
    }

    public static func authenticateDeviceOwner(reason: String, callback: @escaping () -> Void) {
        let localAuthenticationContext = LAContext()
        var error: NSError?
        if localAuthenticationContext.canEvaluatePolicy(.deviceOwnerAuthentication, error: &error) {
            localAuthenticationContext.evaluatePolicy(.deviceOwnerAuthentication, localizedReason: reason) { success, error in
                DispatchQueue.main.async {
                    if success {
                        callback()
                    } else {
                        logger.info("local authentication aborted: \(String(describing: error))")
                    }
                }
            }
        } else {
            logger.info("local authentication unavailable: \(String(describing: error))")
            callback()
        }
    }
}
