import Foundation
import UIKit
import DcCore
import LocalAuthentication

extension URL {
    var isDeltaChatInvitation: Bool {
        if let host, host == Utils.inviteDomain || host == Utils.legacyInviteDomain {
            return true
        } else {
            return false
        }
    }
}
struct Utils {
    public static let inviteDomain = "i.bmchat.example"
    /// Old upstream host that may still appear in QR codes generated by the
    /// bundled native core. BMChat rewrites it on share/copy and never
    /// surfaces it to users.
    public static let legacyInviteDomain = "i.delta.chat"

    /// Replaces a legacy `i.delta.chat` invite host with the BMChat one.
    public static func rewriteInviteLink(_ link: String?) -> String? {
        guard let link else { return nil }
        let httpsPrefix = "https://" + legacyInviteDomain
        let httpPrefix = "http://" + legacyInviteDomain
        if link.hasPrefix(httpsPrefix) {
            return "https://" + inviteDomain + String(link.dropFirst(httpsPrefix.count))
        }
        if link.hasPrefix(httpPrefix) {
            return "https://" + inviteDomain + String(link.dropFirst(httpPrefix.count))
        }
        return link
    }

    /// Removes Delta-Chat artwork (footer wordmark, "δ" centerpiece overlay)
    /// embedded in QR-code SVGs by the bundled native core, and rewrites any
    /// `i.delta.chat` hyperlinks contained within.
    public static func stripDeltaBranding(in svg: String) -> String {
        var out = svg.replacingOccurrences(of: ">get.delta.chat<", with: ">BMChat<")
        let footerPath = #"<path[^>]*id=\"path84310\"[^>]*/>"#
        if let regex = try? NSRegularExpression(pattern: footerPath, options: [.dotMatchesLineSeparators]) {
            let range = NSRange(out.startIndex..., in: out)
            out = regex.stringByReplacingMatches(in: out, range: range, withTemplate: "")
        }
        let centerpiece = #"<g[^>]*transform=\"scale\(1\.1342891,0\.88160947\)\"[^>]*>[\s\S]*?</g>"#
        if let regex = try? NSRegularExpression(pattern: centerpiece, options: [.dotMatchesLineSeparators]) {
            let range = NSRange(out.startIndex..., in: out)
            out = regex.stringByReplacingMatches(in: out, range: range, withTemplate: "")
        }
        out = out.replacingOccurrences(of: "https://i.delta.chat", with: "https://" + inviteDomain)
        out = out.replacingOccurrences(of: "http://i.delta.chat", with: "https://" + inviteDomain)
        return out
    }

    // MARK: - Proxy

    static func isProxy(url proxyURL: URL, dcContext: DcContext) -> Bool {
        let parsedProxy = dcContext.checkQR(qrCode: proxyURL.absoluteString)

        return parsedProxy.state == DC_QR_PROXY
    }

    // MARK: - Email
    static func isEmail(url: URL) -> Bool {
        let mailScheme = "mailto"
        if let scheme = url.scheme {
            return mailScheme == scheme && DcContext.mayBeValidAddr(email: url.absoluteString.substring(mailScheme.count + 1, url.absoluteString.count))
        }
        return false
    }

    static func getEmailFrom(_ url: URL) -> String {
        let mailScheme = "mailto"
        return url.absoluteString.substring(mailScheme.count + 1, url.absoluteString.count)
    }

    public static func getBackgroundImageURL(name: String) -> URL? {
        let fileManager = FileManager.default
        let urls = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask) as [URL]
        guard let identifier = Bundle.main.bundleIdentifier else {
            logger.error("backgroundImageURL: Could not find bundle identifier")
            return nil
        }
        guard let directoryURL = urls.last else {
            logger.error("backgroundImageURL: Could not find directory url for .applicationSupportDirectory in .userDomainMask")
            return nil
        }
        return directoryURL.appendingPathComponent(identifier).appendingPathComponent(name)
    }

    public static func getSafeBottomLayoutInset() -> CGFloat {
        let window = UIApplication.shared.windows.first
        return window?.safeAreaInsets.bottom ?? 0
    }

    public static func getInviteLink(context: DcContext, chatId: Int) -> String? {
        return rewriteInviteLink(context.getSecurejoinQr(chatId: chatId))
    }

    public static func share(message: DcMsg, parentViewController: UIViewController, sourceView: UIView? = nil, sourceItem: UIBarButtonItem? = nil) {
        guard let scrambledURL = message.fileURL else { return }

        let shareURL: URL
        if let filename = message.filename {
            let cleanURL = FileManager.default.temporaryDirectory.appendingPathComponent(filename)
            shareURL = FileHelper.copyIfPossible(src: scrambledURL, dest: cleanURL)
        } else {
            shareURL = scrambledURL
        }

        let objectsToShare: [Any]
        if message.type == DC_MSG_WEBXDC {
            let dict = message.getWebxdcInfoDict()
            let previewImage = message.getWebxdcPreviewImage()
            let previewText = dict["name"] as? String ?? shareURL.lastPathComponent
            objectsToShare = [WebxdcItemSource(title: previewText,
                                               previewImage: previewImage,
                                               url: shareURL)]
        } else {
            objectsToShare = [shareURL]
        }

        let activityVC = UIActivityViewController(activityItems: objectsToShare, applicationActivities: nil)
        activityVC.excludedActivityTypes = [.copyToPasteboard]
        if let sourceItem {
            activityVC.popoverPresentationController?.barButtonItem = sourceItem
        } else if let sourceView {
            activityVC.popoverPresentationController?.sourceView = sourceView
        } else {
            logger.error("set sourceView or sourceItem to avoid iPad crashes")
            return
        }
        parentViewController.present(activityVC, animated: true, completion: nil)
    }

    public static func share(url: String, parentViewController: UIViewController, sourceItem: UIBarButtonItem) {
        guard let url = URL(string: url) else { return }

        Utils.share(url: url, parentViewController: parentViewController, sourceItem: sourceItem)
    }

    public static func share(text: String, parentViewController: UIViewController, sourceItem: UIBarButtonItem) {
        guard let textData = text.data(using: .utf8) else { return }

        // UTF-8 byte order mark, commonly seen in text files. See [List Of file signatures](https://en.wikipedia.org/wiki/List_of_file_signatures)
        var data = Data([0xEF, 0xBB, 0xBF])
        data.append(textData)

        let tempLogfileURL = FileManager.default.temporaryDirectory.appendingPathComponent("deltachat-log.txt")
        try? FileManager.default.removeItem(at: tempLogfileURL)
        try? data.write(to: tempLogfileURL)
        
        Utils.share(url: tempLogfileURL, parentViewController: parentViewController, sourceItem: sourceItem)
    }

    public static func share(url: URL, parentViewController: UIViewController, sourceItem: UIBarButtonItem) {
        let activityVC = UIActivityViewController(activityItems: [url], applicationActivities: nil)
        activityVC.popoverPresentationController?.barButtonItem = sourceItem
        parentViewController.present(activityVC, animated: true, completion: nil)
    }

    public static func share(text: String, parentViewController: UIViewController, sourceView: UIView) {
        let activityVC = UIActivityViewController(activityItems: [text], applicationActivities: nil)
        activityVC.popoverPresentationController?.sourceView = sourceView // iPad crashes without a source
        parentViewController.present(activityVC, animated: true, completion: nil)
    }

    public static func share(url: URL, parentViewController: UIViewController, sourceView: UIView) {
        let activityVC = UIActivityViewController(activityItems: [url], applicationActivities: nil)
        activityVC.popoverPresentationController?.sourceView = sourceView // iPad crashes without a source
        parentViewController.present(activityVC, animated: true, completion: nil)
    }

    public static func authenticateDeviceOwner(reason: String, callback: @escaping () -> Void) {
        let localAuthenticationContext = LAContext()
        var error: NSError?
        if localAuthenticationContext.canEvaluatePolicy(.deviceOwnerAuthentication, error: &error) {
            localAuthenticationContext.evaluatePolicy(.deviceOwnerAuthentication, localizedReason: reason) { success, error in
                DispatchQueue.main.async {
                    if success {
                        callback()
                    } else {
                        logger.info("local authentication aborted: \(String(describing: error))")
                    }
                }
            }
        } else {
            logger.info("local authentication unavailable: \(String(describing: error))")
            callback()
        }
    }
}
