/*
 * BMChat 2.49.97: deep-link trampoline that opens "Settings → Add Second
 * Device" directly when the user scans a QR code generated by the BMChat
 * desktop "Add as Second Device" dialog.
 *
 * The desktop renders a tiny QR encoding `bmchat://second-device`, which
 * is convenient for users whose desktop webcam is unusable: they grab the
 * mobile, scan the desktop's QR with the standard BMChat camera, and
 * land directly on the SENDER_SHOW_QR screen — saving them from digging
 * through the settings menu by hand.
 */
package org.thoughtcrime.securesms.bmchat;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.widget.Toast;
import com.b44t.messenger.DcContext;
import org.thoughtcrime.securesms.BaseActionBarActivity;
import org.thoughtcrime.securesms.ConversationListActivity;
import org.thoughtcrime.securesms.R;
import org.thoughtcrime.securesms.WelcomeActivity;
import org.thoughtcrime.securesms.connect.DcHelper;
import org.thoughtcrime.securesms.qr.BackupTransferActivity;

public class SecondDeviceDeepLinkActivity extends BaseActionBarActivity {

  @Override
  protected void onCreate(Bundle icicle) {
    super.onCreate(icicle);

    DcContext dcContext = DcHelper.getContext(this);
    if (dcContext == null || dcContext.isConfigured() != 1) {
      // No account yet — funnel the user through the regular onboarding
      // instead of crashing inside BackupTransferActivity.
      Toast.makeText(
              this,
              R.string.bmchat_multidevice_helper_qr_need_profile,
              Toast.LENGTH_LONG)
          .show();
      Intent welcome = new Intent(this, WelcomeActivity.class);
      welcome.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
      startActivity(welcome);
      finish();
      return;
    }

    Uri data = getIntent().getData();
    if (data != null && "relay".equalsIgnoreCase(data.getQueryParameter("mode"))) {
      String sid = data.getQueryParameter("sid");
      String key = data.getQueryParameter("key");
      String relay = data.getQueryParameter("relay");
      if (sid != null && key != null && relay != null) {
        Intent relayIntent = new Intent(this, RelaySecondDeviceActivity.class);
        relayIntent.putExtra(RelaySecondDeviceActivity.EXTRA_SID, sid);
        relayIntent.putExtra(RelaySecondDeviceActivity.EXTRA_KEY, key);
        relayIntent.putExtra(RelaySecondDeviceActivity.EXTRA_RELAY, relay);
        relayIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        startActivity(relayIntent);
        finish();
        return;
      }
    }

    // Bring the existing chat list to the front so the back-stack ends up
    // sane after BackupTransferActivity finishes.
    Intent home = new Intent(this, ConversationListActivity.class);
    home.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
    startActivity(home);

    Intent intent = new Intent(this, BackupTransferActivity.class);
    intent.putExtra(
        BackupTransferActivity.TRANSFER_MODE,
        BackupTransferActivity.TransferMode.SENDER_SHOW_QR.getInt());
    intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    startActivity(intent);
    overridePendingTransition(0, 0);
    finish();
  }
}
