export function truncateText(text: string, max_len: number) {
  if (text.length > max_len) {
    return text.slice(0, max_len) + '…'
  } else {
    return text
  }
}

export const BMCHAT_INVITE_SCHEME = 'http'
export const BMCHAT_INVITE_HOST = '5.187.4.132'
export const BMCHAT_INVITE_PATH = '/i'
export const BMCHAT_INVITE_PREFIX = `${BMCHAT_INVITE_SCHEME}://${BMCHAT_INVITE_HOST}${BMCHAT_INVITE_PATH}`
const LEGACY_INVITE_HOSTS = ['i.bmchat.example', 'i.delta.chat']

function legacyPrefixes(host: string): string[] {
  return [
    `https://${host}/#`,
    `https://${host}#`,
    `http://${host}/#`,
    `http://${host}#`,
  ]
}

function bmchatPrefixes(): string[] {
  return [
    `${BMCHAT_INVITE_PREFIX}#`,
    `${BMCHAT_INVITE_PREFIX}/#`,
    `https://${BMCHAT_INVITE_HOST}${BMCHAT_INVITE_PATH}#`,
    `https://${BMCHAT_INVITE_HOST}${BMCHAT_INVITE_PATH}/#`,
  ]
}

/**
 * @returns Whether the `url` is an invite link (for contact or a group).
 *
 * BMChat accepts its own canonical invite link (`http://5.187.4.132/i#…`),
 * any legacy BMChat placeholder host, and upstream `i.delta.chat` so QR codes
 * generated by older builds keep working.
 */
export function isInviteLink(url: string) {
  if (!url || !url.includes('#')) return false
  const lower = url.toLowerCase()
  for (const prefix of bmchatPrefixes()) {
    if (lower.startsWith(prefix)) return true
  }
  for (const host of LEGACY_INVITE_HOSTS) {
    for (const prefix of legacyPrefixes(host)) {
      if (lower.startsWith(prefix)) return true
    }
  }
  return false
}

/**
 * Converts a BMChat/legacy invite hyperlink into the raw `OPENPGP4FPR:` QR
 * payload that *every* Delta Chat core (including the upstream prebuilt core
 * bundled with the desktop client) understands.
 *
 * The BMChat-patched mobile core knows how to decode the canonical
 * `http://5.187.4.132/i#…` host directly, but the desktop client ships the
 * unpatched upstream `@deltachat/stdio-rpc-server`, which only recognises the
 * `https://i.delta.chat/#…` host. Without this normalisation a pasted/scanned
 * BMChat invite link is misinterpreted as a plain `Qr::Url` and never adds the
 * contact. We mirror the core's `decode_ideltachat` transformation here:
 *   1. replace the invite-link prefix with `OPENPGP4FPR:`
 *   2. replace the first `&` (separating fingerprint from params) with `#`
 *
 * Non-invite strings (mailto:, DCACCOUNT:, plain text, already-`OPENPGP4FPR:`
 * payloads, …) are returned unchanged so this is safe to call on any input.
 */
export function inviteLinkToQrText(url: string): string {
  if (!url) return url
  const trimmed = url.trim()
  const lower = trimmed.toLowerCase()
  const prefixes = [
    ...bmchatPrefixes(),
    ...LEGACY_INVITE_HOSTS.flatMap(host => legacyPrefixes(host)),
  ]
  for (const prefix of prefixes) {
    if (lower.startsWith(prefix.toLowerCase())) {
      const fragment = trimmed.slice(prefix.length)
      // `String.replace` with a string argument only replaces the first match,
      // matching the core's `replacen('&', "#", 1)` behaviour.
      return 'OPENPGP4FPR:' + fragment.replace('&', '#')
    }
  }
  return trimmed
}

/**
 * Rewrites any legacy/upstream invite URL to the canonical BMChat link
 * `http://5.187.4.132/i#…`. The cryptographic payload lives in the URL
 * fragment and never reaches the server.
 */
export function rewriteInviteLink(url: string): string {
  if (!url) return url
  const lower = url.toLowerCase()
  for (const host of LEGACY_INVITE_HOSTS) {
    for (const legacy of legacyPrefixes(host)) {
      if (lower.startsWith(legacy)) {
        return `${BMCHAT_INVITE_PREFIX}#${url.slice(legacy.length)}`
      }
    }
  }
  return url
}

/**
 * Removes Delta Chat artwork that the bundled native core embeds in QR-code
 * SVGs (footer wordmark, "δ" centerpiece overlay) and rewrites any legacy
 * invite hyperlinks contained within.
 */
export function stripDeltaBranding(svg: string): string {
  if (!svg) return svg
  let out = svg
    .replace(/>get\.delta\.chat</g, `>BMChat<`)
    .replace(/<path[^>]*id="path84310"[^>]*\/>/gs, '')
    .replace(
      /<g[^>]*transform="scale\(1\.1342891,0\.88160947\)"[^>]*>[\s\S]*?<\/g>/g,
      ''
    )
  for (const host of LEGACY_INVITE_HOSTS) {
    const escaped = host.replace(/\./g, '\\.')
    out = out.replace(
      new RegExp(`https?:\\/\\/${escaped}`, 'g'),
      BMCHAT_INVITE_PREFIX
    )
  }
  return out
}

/**
 * Whether a potentially untrustworthy link,
 * coming from places such as WebXDC apps or HTML email viewer,
 * can and should be handled by the main app.
 * @see `useProcessQR`
 */
export function shouldHandleLinkInMainApp(url: string): boolean {
  return (
    url.startsWith('mailto:') ||
    url.startsWith('openpgp4fpr:') ||
    isInviteLink(url)
  )
}

/**
 * Like [Lodash `throttle`](https://lodash.com/docs/4.17.15#throttle)
 * with default options (`{ leading: true, trailing: true }`).
 */
export function throttle<R, A extends any[]>(
  fn: (...args: A) => R,
  wait: number
) {
  let inThrottle: boolean,
    timeout: ReturnType<typeof setTimeout>,
    lastTime: number
  const ret = (...args: A) => {
    if (!inThrottle) {
      fn(...args)
      lastTime = performance.now()
      inThrottle = true
    } else {
      clearTimeout(timeout)
      timeout = setTimeout(
        () => {
          fn(...args)
          lastTime = performance.now()
        },
        Math.max(wait - (performance.now() - lastTime), 0)
      )
    }
  }
  ret.cancel = () => {
    clearTimeout(timeout)
  }
  return ret
}
