export function truncateText(text: string, max_len: number) {
  if (text.length > max_len) {
    return text.slice(0, max_len) + '…'
  } else {
    return text
  }
}

export const BMCHAT_INVITE_HOST = 'i.bmchat.example'
const LEGACY_INVITE_HOSTS = ['i.delta.chat']

/**
 * @returns Whether the `url` is an invite link (for contact or a group).
 *
 * BMChat accepts both its own invite host and legacy `i.delta.chat` ones to
 * keep compatibility with codes generated by older builds.
 */
export function isInviteLink(url: string) {
  const lower = url.toLowerCase()
  if (!lower.includes('#')) {
    return false
  }
  if (lower.startsWith(`https://${BMCHAT_INVITE_HOST}/`)) {
    return true
  }
  return LEGACY_INVITE_HOSTS.some(host =>
    lower.startsWith(`https://${host}/`)
  )
}

/**
 * Rewrites a Delta-Chat-flavoured invite URL produced by the bundled native
 * core to use the BMChat-controlled host so users never see the upstream
 * domain when sharing or copying the link.
 */
export function rewriteInviteLink(url: string): string {
  if (!url) return url
  for (const host of LEGACY_INVITE_HOSTS) {
    if (url.toLowerCase().startsWith(`https://${host}/`)) {
      return `https://${BMCHAT_INVITE_HOST}${url.slice(`https://${host}`.length)}`
    }
    if (url.toLowerCase().startsWith(`http://${host}/`)) {
      return `https://${BMCHAT_INVITE_HOST}${url.slice(`http://${host}`.length)}`
    }
  }
  return url
}

/**
 * Removes Delta Chat artwork that the bundled native core embeds in QR-code
 * SVGs (footer wordmark, "δ" centerpiece overlay) and rewrites any
 * `i.delta.chat` hyperlinks contained within.
 */
export function stripDeltaBranding(svg: string): string {
  if (!svg) return svg
  return (
    svg
      .replace(/>get\.delta\.chat</g, `>BMChat<`)
      .replace(/<path[^>]*id="path84310"[^>]*\/>/gs, '')
      .replace(
        /<g[^>]*transform="scale\(1\.1342891,0\.88160947\)"[^>]*>[\s\S]*?<\/g>/g,
        ''
      )
      .replace(/https?:\/\/i\.delta\.chat/g, `https://${BMCHAT_INVITE_HOST}`)
  )
}

/**
 * Whether a potentially untrustworthy link,
 * coming from places such as WebXDC apps or HTML email viewer,
 * can and should be handled by the main app.
 * @see `useProcessQR`
 */
export function shouldHandleLinkInMainApp(url: string): boolean {
  return (
    url.startsWith('mailto:') ||
    url.startsWith('openpgp4fpr:') ||
    isInviteLink(url)
  )
}

/**
 * Like [Lodash `throttle`](https://lodash.com/docs/4.17.15#throttle)
 * with default options (`{ leading: true, trailing: true }`).
 */
export function throttle<R, A extends any[]>(
  fn: (...args: A) => R,
  wait: number
) {
  let inThrottle: boolean,
    timeout: ReturnType<typeof setTimeout>,
    lastTime: number
  const ret = (...args: A) => {
    if (!inThrottle) {
      fn(...args)
      lastTime = performance.now()
      inThrottle = true
    } else {
      clearTimeout(timeout)
      timeout = setTimeout(
        () => {
          fn(...args)
          lastTime = performance.now()
        },
        Math.max(wait - (performance.now() - lastTime), 0)
      )
    }
  }
  ret.cancel = () => {
    clearTimeout(timeout)
  }
  return ret
}
